### ISSUE TITLE
Need other languages support

### ISSUE THREAD

**Issue by MasterPetrik** [eiurur/Assist-waifu2x#5]
Need to add language select option.  Of course you can understand japanese, but plugin really need at least english translation. 
Because both waifu2x-caffe and waifu2x site have language selectors, so I think that plugin need it too.   

I can tranlslate to english and  russian, if you add support other languages.

**Comment by eiurur** [comment]
ok. I’ll give it a try. 

Would you translate to russian? 

I 'll translate to english and support i18n.

<br>

Sentence to be translated ↓

![rundll32_2016-09-26_02-20-01](https://cloud.githubusercontent.com/assets/4101830/18816973/c5d84bfc-838f-11e6-8264-c3d4cdd5e1d7.png)

**Comment by eiurur** [comment]
スタイル

イラスト

写真

ノイズ除去

なし

低

中

高

最高

拡大

拡大に失敗したときは元の画像をダウンロードする

拡大した画像はダウンロードせず、新しいタブに表示する

**Comment by MasterPetrik** [comment]
スタイル = "Вид изображения"
イラスト = "Арт"
写真 = "Фотография"

ノイズ除去 = "Устранение шума"
なし = "Нет"
低 = "Слабо"
中 = "Средне"
高 = "Сильно"
最高 = "Очень сильно"

拡大 = "Увеличение"
なし = "Нет"
1.6x 2x

拡大に失敗したときは元の画像をダウンロードする = "Скачать оригинал если не удастся увеличить"

拡大した画像はダウンロードせず、新しいタブに表示する = "Открывать изображение в новой вкладке вместо скачивания"

When translating into other languages, it is worth remembering that the same text is translated from Japanese to English will occupy more space in the interface, and the Russian text will occupy more space than English text in any condition. This is normal. Please consider this when translating, and may need to expand the interface, thank you. The Russian translation is based on the translation http://waifu2x.udp.jp/index.ru.html
and terms are completely identical.

**Comment by eiurur** [comment]
I implemented i18n and uploaded the zip file to Chrome WebStore as v0.8.0.

Thank you so much!!

<br>

## ja

![2016-09-27_00-31-08](https://cloud.githubusercontent.com/assets/4101830/18840517/cc4ffb32-8449-11e6-9d13-b577fb5a1bc9.png)

## en

![2016-09-27_00-31-19](https://cloud.githubusercontent.com/assets/4101830/18840521/d0fc6558-8449-11e6-8d92-c342a4aa2bdf.png)

## ru

![2016-09-27_00-31-28](https://cloud.githubusercontent.com/assets/4101830/18840524/d33641cc-8449-11e6-952d-b7954432cd57.png)

**Comment by MasterPetrik** [comment]
Well done! Thanks.

**Comment by MasterPetrik** [comment]
![image](https://cloud.githubusercontent.com/assets/22294259/18852330/a2822d8a-8448-11e6-98ff-4dbda81a952a.png)

looks like language selector in default condition(right after installing for example) just empty. I think it might ba a bug. When you select any language all work normal.

It might be better to set default language as english, i guess

**Comment by eiurur** [comment]
I fixed the parts you instructed me to.

> 923183e3307cc4a1e70aae461a0fc67fa922655c

Thank you for all your assistance!!
